### ISSUE TITLE
Suggested issues to be resolved

### ISSUE THREAD

**Issue by chimake** [Moses-chibuike/Portfolio-microverse#4]
Excellent job on the codebase. Here are some polite suggestions we will like to point out;
**HTML**
1. Line 14 should be wrapped within a nav tag
2. Header tags were used properly
3. Issue with file naming on lines 57, 80, 103, 144,149,153,157,164,169
4. Wrong Alt names for different files, 57, 149,153,157,175,176,177

**CSS**
1. Nice declare color variables in the css file
2. Hierarchy in placing height and width before other rules on line 28
3. Issues on file naming on line 40 because of SEO ranking

**Comment by Moses-chibuike** [comment]
Thanks for the reviews, the issues has been fixed
